# Generated by Django 5.2.11 on 2026-03-03 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("budget", models.PositiveIntegerField()),
                ("timeline_days", models.PositiveIntegerField()),
                ("category", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("awaiting_client_review", "Awaiting review"),
                            ("completed", "Completed"),
                            ("closed_refunded", "Closed refunded"),
                            ("disputed", "Disputed"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                ("timeline_days", models.PositiveIntegerField()),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("withdrawn", "Withdrawn"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "freelancer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="selected_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_for",
                to="projects.proposal",
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["project", "status", "-created_at"],
                name="idx_prop_proj_status_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="proposal",
            constraint=models.UniqueConstraint(
                fields=("project", "freelancer"), name="uq_proposal_project_freelancer"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "category", "-created_at"],
                name="idx_project_status_cat_created",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "open",
                            "in_progress",
                            "awaiting_client_review",
                            "completed",
                            "closed_refunded",
                            "disputed",
                        ],
                    )
                ),
                name="ck_project_valid_status",
            ),
        ),
    ]
