# Generated by Django 5.2.11 on 2026-03-03 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectdeliverable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["status", "-created_at"], name="idx_project_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["-created_at"], name="idx_project_created"),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["project", "status"], name="idx_prop_project_status"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(
                fields=["freelancer", "status"], name="idx_prop_freelancer_status"
            ),
        ),
        migrations.AddIndex(
            model_name="proposal",
            index=models.Index(fields=["-created_at"], name="idx_prop_created"),
        ),
    ]
