# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_category_project_required_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contact_info",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
