# Generated by Django 5.2.15 on 2026-06-10 07:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_contact_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="project",
            name="ck_project_valid_status",
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reviewing", "Reviewing"),
                    ("agreed", "Agreed"),
                    ("paid", "Paid"),
                    ("delivered", "Delivered"),
                    ("in_progress", "In progress"),
                    ("awaiting_client_review", "Awaiting review"),
                    ("completed", "Completed"),
                    ("closed_refunded", "Closed refunded"),
                    ("disputed", "Disputed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "open",
                            "reviewing",
                            "agreed",
                            "paid",
                            "delivered",
                            "in_progress",
                            "awaiting_client_review",
                            "completed",
                            "closed_refunded",
                            "disputed",
                        ],
                    )
                ),
                name="ck_project_valid_status",
            ),
        ),
    ]
