# Generated by Django 5.2.12 on 2026-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("suspended", "Suspended"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_type",
            field=models.CharField(
                blank=True,
                choices=[("individual", "Хувь хүн"), ("business", "Байгууллага")],
                max_length=20,
            ),
        ),
    ]
