# Generated by Django 5.2.11 on 2026-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform_fee_pct", models.PositiveSmallIntegerField(default=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
