# Generated by Django 5.2.11 on 2026-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsetting",
            name="partial_escrow_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="platformsetting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("platform_fee_pct__gte", 0), ("platform_fee_pct__lte", 30)
                ),
                name="valid_fee_bounds",
            ),
        ),
    ]
