# Generated by Django 5.2.11 on 2026-03-03 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_financialauditlog_idempotencykey"),
        ("projects", "0003_project_idx_project_status_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["project", "-created_at"], name="idx_dispute_project_created"
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["status", "project"], name="idx_escrow_status_project"
            ),
        ),
        migrations.AddIndex(
            model_name="escrow",
            index=models.Index(
                fields=["project", "status", "-created_at"],
                name="idx_escrow_proj_stat_created",
            ),
        ),
    ]
